### ISSUE TITLE
Phpspec version 3.0.0 Laravel 5.6

### ISSUE THREAD

**Issue by AldoGArenas** [juanjoc333/rfc-facil-php#1]
Tengo un problema al instalar via composer rfc facil ya que me pide versión 3.0.0 mas sin embargo en laravel 5.6 no es posible instalar dicha versión de phpspec.

Quedo atento a tu respuesta saludos!

**Comment by juanjoc333** [comment]
En revisión, a que versión debería actualizarlo?

**Comment by Gustavinho** [comment]
Hola buenas tardes, mismo caso por aca, me parece que laravel 5.6 utiliza la version 4 de phpspec

**Comment by maestro362** [comment]
Fue resuelto este problema???
