### ISSUE TITLE
Error al obtener RFC de nombre con artículos y preposiciones

### ISSUE THREAD

**Issue by hurbanom** [juanjoc333/rfc-facil-php#2]
Al tratar de obtener el RFC de una persona de nombre María del Rosario, obtiene el RFC mal, al hacer el debugueo es por que al intentar eliminar los articulos y preposiciones del nombre con el str_replace encuentra en el arreglo primero la preposion DE y no DEL por lo que el nombre lo deja como MARIAL ROSARIO.

Sugiero hacer un cambio en la funcion **removeSpecialParticles** del archivo **NaturalPersonTenDigitsCalculator.php** para que quede de la siguiente forma:

```
protected function removeSpecialParticles($word, $specialParticle){
        foreach ($specialParticle as $particle){
            $particlePositions = ["/".$particle . " \b/", "/ " . $particle."\b/"];
            foreach ($particlePositions as $particlePosition){
                $word = preg_replace($particlePosition, "", $word);
            }
        }
        return $word;
}
```

**Comment by juanjoc333** [comment]
Me parece bien, déjame correr las pruebas y actualizar esta función

**Comment by juanjoc333** [comment]
Se hizo el cambio en el método

Saludos
