### ISSUE TITLE
Phpspec version 3.0.0 Laravel 5.8

### ISSUE THREAD

**Issue by aumeli74** [juanjoc333/rfc-facil-php#3]
Hola ,como puedo evitar este error al agregar con composer el paquete a mi  proyecto marca error por conflicto, laravel  5.4 en adelante  utiliza phpspec ^4.0 por lo que pude ver en la documentacion

    - Can only install one of: phpspec/phpspec[3.4.x-dev, 4.3.4].
    - juanjoc333/rfc-facil-php 1.0 requires phpspec/phpspec ^3.0 -> satisfiable by phpspec/phpspec[3.4.x-dev].
    - Installation request for juanjoc333/rfc-facil-php ^1.0 -> satisfiable by juanjoc333/rfc-facil-php[1.0].
    - Installation request for phpspec/phpspec (locked at 4.3.4, required as ^4.0) -> satisfiable by phpspec/phpspec[4.3.4].

Saludos

**Comment by juanjoc333** [comment]
Se sube dependencia de phpspec de 3.4 a 4
