### ISSUE TITLE
Homo clave en personas morales

### ISSUE THREAD

**Issue by balamcan** [juanjoc333/rfc-facil-php#4]
Hola, me gustó mucho su libreria, y detecté que en veces no sale la misma homoclave por la parte de la razon social, no sé a que se deba, sin embargo a veces coincide y otras no, solo para reportar el detalle, gracias por la libreria! super genial

**Comment by balamcan** [comment]
falta lo de retirar si trae s.a. de c.v. si no te genera una incorrecta

**Comment by juanjoc333** [comment]
Hola, ¿podrías poner algunos ejemplos para realizar pruebas y reproducir los errores que mencionas?

**Comment by juanjoc333** [comment]
Se hace push de tag v1.3, creo que debería tomar el cambio

Saludos

**Comment by balamcan** [comment]
:tada: muchas gracias! checaré cambios

**Comment by balamcan** [comment]
![image](https://user-images.githubusercontent.com/3271775/118027581-536de080-b31f-11eb-9efb-620014677e2c.png)

**Comment by juanjoc333** [comment]
Listo, se publica la v1.3, creo que ese es el problema

**Comment by balamcan** [comment]
creo que hace falta hacer el cambio dentro de la configuracion donde publicas el paquete de composer, por que me sigue agarrando la version 1.0

![image](https://user-images.githubusercontent.com/3271775/118031948-561f0480-b324-11eb-83dd-283c91e17e5d.png)

disculpa las molestias Juan...

**Comment by juanjoc333** [comment]
Caramba... Cierto no estaba especificada la versión en el composer.json, se agrega en el ultimo commit

Saludos

**Comment by balamcan** [comment]
Hola Juan, desconozco por que no obtiene la version 1.3, aunque hiciste la modificacion correspondiente, el composer require no detecta la nueva version:
sudo composer require juanjoc333/rfc-facil-php
![image](https://user-images.githubusercontent.com/3271775/118314128-ec803100-b4b0-11eb-8183-91e804edc916.png)

Ya falta poquito para que se haga el deploy de la nueva version, gracias por el apoyo y por la aportacion de este componente! 
Obviamente dejo tu reconocimiento y tu referencia en el proyecto que lo estoy utilizando.

**Comment by juanjoc333** [comment]
No era ninguna de esos detalles, faltaba actualizar el repositorio en Packagist además que me mandaba algunos errores. Actualmente ya quedó configurada la actualización automática siendo la v1.4 la ultima. Espero que con esto quede arreglado el problema de la actualización de la dependencia.

![Screen Shot 2021-05-15 at 6 06 12](https://user-images.githubusercontent.com/7155814/118358691-a0330080-b545-11eb-9b5b-9cb95c558d0c.png)

![Screen Shot 2021-05-15 at 6 18 52](https://user-images.githubusercontent.com/7155814/118358661-82fe3200-b545-11eb-86c2-e806707c70e5.png)

Saludos y gracias por la referencia

**Comment by balamcan** [comment]
Muchas gracias! ya funcionó la parte de la actualizacion, ahora tengo broncar por la parte de el sistema que estamos desarrollando, la version es vieja de PHP, y ahi ya no es cuestion tuyo del componente, dejo cerrado el issue y gracias por la respuesta y atencion del componente. buen dia!
