### ISSUE TITLE
Problema al instalar via Composer

### ISSUE THREAD

**Issue by xSirLalo** [juanjoc333/rfc-facil-php#6]
`Using version ^1.0 for juanjoc333/rfc-facil-php
./composer.json has been updated
Running composer update juanjoc333/rfc-facil-php
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpspec/phpspec[3.0.0, ..., 3.2.1] require sebastian/exporter ^1.0 -> found sebastian/exporter[1.0.0, ..., 1.2.2] but the package is fixed to 4.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - phpspec/phpspec[3.2.2, ..., 3.2.3] require sebastian/exporter ^1.0 || ^2.0 -> found sebastian/exporter[1.0.0, ..., 1.2.2, 2.0.0] but the package is fixed to 4.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - phpspec/phpspec[3.3.0, ..., 3.4.3] require sebastian/exporter ^1.0 || ^2.0 || ^3.0 -> found sebastian/exporter[1.0.0, ..., 1.2.2, 2.0.0, 3.0.0, ..., 3.1.3] but the package is fixed to 4.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - juanjoc333/rfc-facil-php 1.0 requires phpspec/phpspec ^3.0 -> satisfiable by phpspec/phpspec[3.0.0, ..., 3.4.3].
    - Root composer.json requires juanjoc333/rfc-facil-php ^1.0 -> satisfiable by juanjoc333/rfc-facil-php[1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by juanjoc333** [comment]
Creo que debes actualizar tu dependencia de **sebastian/exporter** a la más reciente, se realiza comprobación de instalación vía Composer y no presentó ningún problema 

➜ test cat composer.json
```
{
    "name": "juanjoc/test",
    "authors": [
        {
            "name": "Juan José Cortés Guzmán",
            "email": "juan.cortes@suma.mx"
        }
    ],
    "require": {
        "sebastian/exporter": "^3.1",
        "juanjoc333/rfc-facil-php": "^1.0"
    }
}
```
